resources:
  repositories:
  - repository: Celestia
    type: github
    endpoint: GithubAuth
    name: celestiamobile/Celestia
    ref: develop
  - repository: apple-android-dependencies
    type: github
    endpoint: GithubAuth
    name: celestiamobile/apple-android-dependencies
  - repository: emsdk
    type: github
    endpoint: GithubAuth
    name: emscripten-core/emsdk

trigger:
- main

stages:
- stage: Build
  displayName: 'Build'
  dependsOn: []
  jobs:
  - template: jobs/build.yml

